[package]
name = "machete"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27.2", default-features = false, features = [  "web_screen_reader" ] }
egui = { version = "0.27.2", features = ["callstack", "default", "log"] }
egui_extras = { version = "0.27.2", features = ["default", "image"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1.0.117"
primitive-types = "0.12.2"
base58 = "0.2"
hex = "0.4.3"
chrono = {version = "0.4.38", features = ["serde"]}
itertools = "0.13.0"

regex = "1.10.4"
lazy_static = "1.4.0"

getrandom = "0.2.15"

[features]
default = ["offline"]

offline = ["eframe/glow"]
