version: '3'
services:
  postgres_db:
    image: postgres:alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: machete
      POSTGRES_PASSWORD: machete
volumes:
  postgres-data:
