name: "Deploy to Cloudflare Pages"

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Deploy Env
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Clone and checkout repository
        uses: actions/checkout@v3

      - name: Cache Cargo directories and build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.79.0  # Specify the Rust version you need
          components: cargo  # Ensure cargo is included
          profile: minimal  # Optionally reduce installation size
          override: true

      - name: Build web code
        env:
          NODE_ENV: production
        run: ./scripts/build_web.sh
    
      - name: Publish to Cloudflare Pages
        id: cloudflare
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: machete
          directory: web
          branch: master
